- name: Install RabbitMQ
  hosts: rabbitmq
  become: yes
  tasks:
  - name: Configure RabbitMQ YUM Repos
    ansible.builtin.shell:
    loop:
    - "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"
    - "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"

  - name: Install RabbitMQ
    ansible.builtin.yum:
      name: rabbitmq-server
      state: installed

  - name: Start RabbitMQ Service
    ansible.builtin.service:
     name: rabbitmq-server
     state: started
     enabled: true

  - name: create rabbitmq user
    ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123

  - name: setup permission
    ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
