- name: Install redis
  hosts: redis
  become: yes
  tasks:
  - name: Install redis
    ansible.builtin.yum:
      name: redis
      state: installed

  - name: enable rempte connection to redis
    ansible.builtin.replace:
      path: /etc/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: Start the redis
    ansible.builtin.service:
      name: redis
      state: restarted
      enabled: yes