- name: Install Shipping Component
  hosts: shipping
  become: yes
  tasks:
  - name: Install Maven
    ansible.builtin.yum:
      name: maven
      state: installed

  - name: check user exits or not
    ansible.builtin.command: id roboshop
    register: out  #out is variable name
    ignore_errors: true

  - when: out.rc != 0
    name: create user roboshop
    become: yes #we need sudo access for this task only
    ansible.builtin.user:
      name: roboshop

    # check the exist or not
  - name: check /app directory exist or not
    ansible.builtin.stat:
      path: /app
    register: directory # we run the above command and output will stored inside this "directory" variable

  - when: directory.stat.exists == False 
    name: Create /app directory 
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download the shipping Artifact
    ansible.builtin.get_url:
      url:  https://roboshop-builds.s3.amazonaws.com/shipping.zip
      dest: /tmp
      
  - name: extract shipping Artifact
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip   
      dest: /app
      remote_src: yes




