- name: install user
  hosts: user
  become: yes
  tasks:
  - name: NPM source
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: Install Node.Js
    ansible.builtin.yum:
      name: nodejs
      state: installed

  - name: check user exits or not
    ansible.builtin.command: id roboshop
    register: out  #out is variable name
    ignore_errors: true

  - when: out.rc != 0
    name: create user roboshop
    become: yes #we need sudo access for this task only
    ansible.builtin.user:
      name: roboshop

  - # check the exist or not
  - name: check /app directory exist or not
    ansible.builtin.stat:
      path: /app
    register: directory # we run the above command and output will stored inside this "directory" variable

  - name: print the directory stat
    ansible.builtin.debug:
      msg: "output {{directory}}"

  - when: directory.stat.exists == False 
    name: Create /app directory 
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download the user Artifact
    ansible.builtin.get_url:
      url:  https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp

  - name: extract user Artifact
    ansible.builtin.unarchive:
      src: /tmp/user.zip     
      dest: /app
      remote_src: yes

  - name: Install the dependencies
    ansible.builtin.command: npm install 
    args:
      chdir: /app

  - name: copy User Service
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: reload the service
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: setup MongoDB repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb-client
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed

  - name: Load user Schema
    ansible.builtin.command: mongo --host mongodb.joindevops.shop < /app/schema/user.js

  - name: Start the user
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes

 